### ISSUE TITLE
Listing your package on Pulsar

### ISSUE THREAD

**Issue by Daeraxa** [asmaloney/language-txl#1]
Hello, this is Daeraxa from the Pulsar Team.

[Pulsar](https://github.com/pulsar-edit/pulsar) is an actively developed fork of Atom and one of our major efforts is to preserve the ecosystem of [Community Packages](https://web.pulsar-edit.dev/) that were previously published on Atom.io

While we want to list every single package that existed on Atom's Package Repository, we wanted to respect the license of each package within and ensure to only list packages that either the author has agreed for us to or packages that have a license that specify that redistribution is okay.

That is exactly why we are contacting you today, it seems your package `language-txl` has a license that makes it hard for us to determine if we should be listing it for redistribution.

All that needs to happen for you as a package maintainer is for you to give authorization for us to list your package. Just reply to this issue either way and we will respect your wishes.

Otherwise within 3 weeks, if there is no response, we will assume the answer is no and remove your package from the Pulsar Package Registry.

And if you've missed the deadline we have and still want your package to be published, feel free to [republish to Pulsar](https://pulsar-edit.dev/docs/launch-manual/sections/core-hacking/#publishing).

Thanks a ton for your time, hope you have a great day!

**Comment by asmaloney** [comment]
Hey @Daeraxa. Sure - no problem! I added an MIT license.

There might be _one_ person out there who might use this language 😄 

Best of luck with your project!

**Edit:** I also updated the README to point at Pulsar.

**Comment by Daeraxa** [comment]
Awesome, thank you. If nothing else it got me to have a look at txl, definitely interesting :)

**Comment by asmaloney** [comment]
It's a super-cool language if you need to do any semantically correct changes to source or other structured text. We used it to do all kinds of design recovery, dialect migration, and static analysis cleanups of large [COBOL](https://en.wikipedia.org/wiki/COBOL), [PL/I](https://en.wikipedia.org/wiki/PL/I), and [RPG](https://en.wikipedia.org/wiki/IBM_RPG) systems.

**Comment by Daeraxa** [comment]
I'll certainly keep it in mind, into the notes it goes :)
